version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.8.0a4-stretch
    steps:
      - run:
          name: Install dependencies (debian)
          command: |
            sudo apt-get update
            sudo apt-get install gcc gfortran make binutils binutils-dev libc6-dev libbsd-dev
            sudo apt-get install libnetcdf-dev libhdf5-dev
            sudo apt-get install ruby rake
            sudo apt-get install python-dev libpython-dev
            sudo apt-get install python-netcdf4
            sudo apt-get install python-unittest2
      - run:
          name: Checkout cdo-bindings
          command: |
            git clone https://github.com/Try2Code/cdo-bindings.git
      - run:
          name: Install conda, CDO and environements for Python 2.7/3.6/3.7
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && bash miniconda.sh -b -p $HOME/miniconda
            export PATH="$HOME/miniconda/bin:$PATH"
            hash -r
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            conda info -a
            conda config --add channels conda-forge
            cd cdo-bindings
            conda env create --file .travis-py2.7.yml
            conda env create --file .travis-py3.6.yml
            conda env create --file .travis-py3.7.yml
      - run:
          name: Install dependencies (rake)
          command: |
            gem install minitest colorize facets --user
      - run:
          name: Run Tests Python 2.7
          command: |
            source activate test_env_py27
            conda update --all
            cdo -V
            type -p cdo
            python --version
            rake testPython CDO=$(type -p cdo) NO_COLOR=1
      - run:
          name: Run Tests Python 3.6
          command: |
            source activate test_env_py36
            conda update --all
            cdo -V
            type -p cdo
            python --version
            rake testPython CDO=$(type -p cdo) NO_COLOR=1
      - run:
          name: Run Tests Python 3.7
          command: |
            source activate test_env_py37
            conda update --all
            cdo -V
            type -p cdo
            python --version
            rake testPython CDO=$(type -p cdo) NO_COLOR=1
