version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.8.0a4-stretch
    steps:
      - run:
          name: Install CDO via conda
          command: |
            sudo apt-get updatae
            sudo apt-get install libnetcdf-dev libhdf5-dev
            sudo apt-get install ruby rake
            sudo apt-get install python-netcdf4
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && bash miniconda.sh -b -p $HOME/miniconda
            export PATH="$HOME/miniconda/bin:$PATH"
            hash -r
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            conda info -a
            conda config --add channels conda-forge
            conda install cdo
            conda update --all
      - run:
          name: Install dependencies
          command: | 
            pip install six matplotlib numpy xarray unittest2
      - run:
          name: Test
          command: |
            python --version
            rake testPython CDO=$(type -p cdo) NO_COLOR=1
